"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import type { FinanceCreditLine } from "../types/planning.types";

type Raw = { id:string; credit_line_id:string; due_date:string; planned_principal_eur:number; expected_interest_eur:number; expected_fees_eur:number; concept:string; reference:string|null; status:string; linked_repayment_group_id:string|null; finance_credit_lines?:{bank_name?:string;line_name?:string} };
const eur=(value:number)=>new Intl.NumberFormat("es-ES",{style:"currency",currency:"EUR"}).format(value);

export function CreditLinePlannedMaturitiesSection({lines,onSaved}:{lines:FinanceCreditLine[];onSaved:()=>Promise<void>}) {
  const [rows,setRows]=useState<Raw[]>([]); const [canManage,setCanManage]=useState(false); const [open,setOpen]=useState(false); const [error,setError]=useState<string|null>(null);
  const [lineId,setLineId]=useState(lines[0]?.id??""); const [dueDate,setDueDate]=useState(""); const [principal,setPrincipal]=useState(""); const [interest,setInterest]=useState("0"); const [fees,setFees]=useState("0"); const [concept,setConcept]=useState(""); const [reference,setReference]=useState(""); const [notes,setNotes]=useState("");
  const idempotencyKey=useRef<string|null>(null);
  async function load(){const response=await fetch("/api/finance/credit-lines/planned-maturities?status=planned",{cache:"no-store"});const json=await response.json();if(!response.ok)throw new Error(json.error);setRows(json.data??[]);setCanManage(Boolean(json.permissions?.canManage));}
  useEffect(()=>{void load().catch(value=>setError(value instanceof Error?value.message:"Error"));},[]);
  const selected=lines.find(line=>line.id===lineId); useEffect(()=>{if(selected&&!concept)setConcept(`Devolución de crédito – ${selected.bankName}`);},[selected,concept]);
  const byLine=useMemo(()=>new Map(lines.map(line=>[line.id,rows.filter(row=>row.credit_line_id===line.id&&row.status==="planned"&&!row.linked_repayment_group_id).reduce((sum,row)=>sum+Number(row.planned_principal_eur),0)])),[lines,rows]);
  function toggle(){if(open){idempotencyKey.current=null;setOpen(false);}else{idempotencyKey.current=crypto.randomUUID();setOpen(true);}}
  async function submit(event:React.FormEvent){event.preventDefault();setError(null);if(!idempotencyKey.current)idempotencyKey.current=crypto.randomUUID();const payload={creditLineId:lineId,dueDate,plannedPrincipalEur:Number(principal),expectedInterestEur:Number(interest),expectedFeesEur:Number(fees),concept,reference:reference||null,notes:notes||null,idempotencyKey:idempotencyKey.current};const response=await fetch("/api/finance/credit-lines/planned-maturities",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const json=await response.json();if(!response.ok){setError(json.error);return;}idempotencyKey.current=null;setOpen(false);setPrincipal("");await load();await onSaved();}
  return <section className="rounded-xl border border-violet-200 bg-white p-4">
    <div className="flex items-center justify-between"><div><h2 className="font-bold">Vencimientos previstos de líneas</h2><p className="text-xs text-slate-500">Previsiones de tesorería; no ejecutan pagos ni cambian saldos.</p></div>{canManage?<button onClick={toggle} className="rounded bg-violet-700 px-3 py-2 text-xs font-semibold text-white">{open?"Cancelar":"Registrar vencimiento de línea"}</button>:null}</div>
    <div className="mt-3 grid gap-2 md:grid-cols-3">{lines.map(line=>{const planned=byLine.get(line.id)??0;const missing=Math.max(line.usedAmount-planned,0);const excess=Math.max(planned-line.usedAmount,0);return <div key={line.id} className={`rounded border p-3 text-xs ${excess>0?"border-amber-400 bg-amber-50":""}`}><b>{line.bankName} · {line.lineName}</b><div>Usado: {eur(line.usedAmount)}</div><div>Principal previsto: {eur(planned)}</div><div>Sin calendarizar: {eur(missing)}</div><div className={excess>0?"font-bold text-amber-800":""}>Exceso calendarizado: {eur(excess)}</div></div>})}</div>
    <div className="mt-3 max-h-64 space-y-1 overflow-auto">{rows.map(row=><div key={row.id} className="grid grid-cols-[100px_1fr_auto] gap-2 rounded bg-slate-50 px-2 py-1 text-xs"><span>{row.due_date}</span><span>{row.finance_credit_lines?.bank_name} · {row.concept}{row.reference?` · ${row.reference}`:""}</span><b>{eur(Number(row.planned_principal_eur)+Number(row.expected_interest_eur)+Number(row.expected_fees_eur))}</b></div>)}</div>
    {open?<form onSubmit={submit} className="mt-4 grid gap-2 rounded border p-3 md:grid-cols-3"><select value={lineId} onChange={event=>{setLineId(event.target.value);const line=lines.find(item=>item.id===event.target.value);setConcept(line?`Devolución de crédito – ${line.bankName}`:"");}}>{lines.map(line=><option key={line.id} value={line.id}>{line.bankName} · {line.lineName}</option>)}</select><input required type="date" value={dueDate} onChange={event=>setDueDate(event.target.value)}/><input required type="number" min="0.01" step="0.01" placeholder="Principal" value={principal} onChange={event=>setPrincipal(event.target.value)}/><input type="number" min="0" step="0.01" placeholder="Intereses" value={interest} onChange={event=>setInterest(event.target.value)}/><input type="number" min="0" step="0.01" placeholder="Comisiones" value={fees} onChange={event=>setFees(event.target.value)}/><input required maxLength={250} value={concept} onChange={event=>setConcept(event.target.value)}/><input maxLength={250} placeholder="Referencia" value={reference} onChange={event=>setReference(event.target.value)}/><input maxLength={2000} placeholder="Notas" value={notes} onChange={event=>setNotes(event.target.value)}/><div className="text-xs">Salida prevista: {eur((Number(principal)||0)+(Number(interest)||0)+(Number(fees)||0))}</div><button className="rounded bg-slate-900 p-2 text-white">Guardar previsión</button></form>:null}
    {error?<p className="mt-2 text-xs text-red-700">{error}</p>:null}
  </section>;
}
