-- Migration application order for finance credit-line maturities (DO NOT APPLY HERE).
-- Lexicographic + dependency order for pending finance-related migrations before/around 20260727+.
--
-- PREREQUISITE BASE (already historical in many envs; verify presence):
--   finance_planning_base.sql
--   finance_credit_lines_grouped_repayments_schema.sql
--   finance_credit_lines_ledger_rpc.sql
--   finance_planning_read_rls_policies.sql
--   finance_supplier_payment_finance_rpc.sql
--
-- PENDING / ORDERED APPLY (finance payment + maturity stack):
--   1. sql/diagnostics/credit_line_maturities_hardening_preflight.sql   (SELECT only)
--   2. Prior finance migrations still pending before 20260727 (supplier payment stack):
--        20260721_supplier_payment_actual_fields.sql
--        20260721_supplier_payment_mark_paid_rpc.sql
--        20260721_supplier_payment_sync_plan_rpc.sql
--        20260721_supplier_payment_t_atomic_pay_finance.sql
--        20260721_z_remove_order_fx_from_operational_flow.sql
--   3. sql/migrations/20260722_linked_purchase_payment_batches.sql
--   4. sql/migrations/20260727_credit_line_maturities_phase1.sql
--   5. sql/migrations/20260728_harden_credit_line_maturity_execution.sql
--   6. OPTIONAL: sql/migrations/20260727_credit_line_legacy_opening_balance_rpc.sql
--        (admin regularization; independent of harden; apply after phase1 schema exists)
--   7. SELECT pg_notify('pgrst', 'reload schema');
--   8. Transactional diagnostic with BEGIN…ROLLBACK (no commit)
--
-- Do NOT apply only the two 20260727 files in isolation: linked payment batches (20260722)
-- and earlier 20260721 supplier-payment RPCs are required dependencies for financed drawdowns.
-- Lexicographic note: 20260727_legacy sorts before 20260728; if applying by filename alone,
-- run harden after phase1 and treat legacy RPC as optional admin tooling.
--
-- Unrelated 202607* Amazon/inventory/order migrations may exist in the same folder;
-- do not skip finance dependencies above when validating credit-line maturities.
--
-- This file is documentation only.
SELECT 1;
