import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import * as policy from './allOrdersSyncPolicy.ts';
import * as coordinator from './allOrdersSyncCoordinator.ts';
const require=createRequire(import.meta.url),ts=require('typescript');
function load(path,deps){const loadedModule={exports:{}};const js=ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;new Function('require','module','exports',js)(name=>{if(name in deps)return deps[name];throw Error('Unexpected dependency: '+name)},loadedModule,loadedModule.exports);return loadedModule.exports}
const response={NextResponse:{json:(body,opts)=>({body,status:opts?.status??200})}};
test('manual route keeps requested range; explicit 409 instead of unrelated resume',async()=>{let resumes=0,requested;const start=async p=>{requested=p;throw Error('ALL_ORDERS_RANGE_CONFLICT')};const manual=load('app/api/amazon/reports/all-orders/import/route.ts',{'next/server':response,'@/modules/amazon-sp-api/config':{getMissingSpApiEnvKeys:()=>[]},'@/modules/amazon-sp-api/errors':{mapGenericError:e=>({message:e.message})},'@/server/supabase/routeClient':{createSupabaseRouteClient:()=>({auth:{getUser:async()=>({data:{user:{id:'u'}}})}})},'@/modules/amazon-sp-api/allOrdersSalesSyncService':{startAllOrdersSync:start,resumeAllOrdersSync:async id=>{resumes++;return {status:'PENDING',jobId:id}}}});const r=await manual.POST({json:async()=>({fromDate:'2026-07-01',toDate:'2026-07-02'})});assert.equal(r.status,409);assert.deepEqual(requested,{fromDate:'2026-07-01',toDate:'2026-07-02'});assert.equal(resumes,0);const resumed=await manual.POST({json:async()=>({jobId:'j'})});assert.equal(resumed.status,202);assert.equal(resumes,1)});
test('dedicated recovery idle never generates; auth gates all operations',async()=>{process.env.CRON_SECRET='local-test';let starts=0,resumes=0;const http=load('modules/amazon-sp-api/allOrdersHttp.ts',{'node:crypto':require('node:crypto'),'next/server':response,'./allOrdersSyncPolicy':policy,'./allOrdersSalesSyncService':{findOpenAllOrdersSyncJobId:async()=>null,resumeAllOrdersSync:async()=>{resumes++},startAllOrdersSync:async()=>{starts++}},'@/server/supabase/adminClient':{supabaseAdmin:{}}});const request={headers:new Headers({authorization:'Bearer local-test'})};assert.equal((await http.ordersRecovery(request)).body.status,'IDLE');assert.equal(starts,0);assert.equal(resumes,0);assert.equal((await http.ordersGeneration({headers:new Headers()})).status,401);assert.equal(starts,0)});
test('runtime default disabled makes zero Amazon/DB calls; known job terminal is read only',async()=>{let calls=0;const state=policy.buildOrdersState('2026-07-01','2026-07-02',['A1RKKUPIHCS9HS'],new Date('2026-08-01'));const repo={readOrdersOperation:async()=>({status:'COMPLETED',state:{...state,windows:state.windows.map(w=>({...w,phase:'COMPLETE'}))}})};const runtime=load('modules/amazon-sp-api/allOrdersSalesSyncService.ts',{'./config':{DEFAULT_EU_MARKETPLACE_IDS:['A1RKKUPIHCS9HS']},'./reportsClient':{createReport:async()=>{calls++},getReport:async()=>{calls++}},'./allOrdersReportParser':{ALL_ORDERS_REPORT_TYPE:'GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL'},'./allOrdersDocument':{},'./operationalAmazonIdentityRepository':{},'./allOrdersSyncPolicy':policy,'./allOrdersSyncCoordinator':coordinator,'./allOrdersSyncRepository':repo});delete process.env.AMAZON_ORDERS_CANONICAL_ENABLED;await assert.rejects(runtime.resumeAllOrdersSync('j'),/DISABLED/);assert.equal(calls,0);process.env.AMAZON_ORDERS_CANONICAL_ENABLED='true';assert.equal((await runtime.resumeAllOrdersSync('j')).status,'COMPLETED');assert.equal(calls,0);delete process.env.AMAZON_ORDERS_CANONICAL_ENABLED});
