import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {buildAmazonEconomicForecastV2,buildAmazonFutureProductLine,buildAmazonRealMtd} from "./amazonEconomicForecastV2.ts";
import {createProductFeesClient,resetProductFeesCacheForTests} from "../../amazon-sp-api/productFeesClient.ts";
import {parseFbaFeePreview} from "../../amazon-sp-api/fbaFeePreviewService.ts";

const ecb={referenceDate:"2026-08-13",fetchedAt:"2026-08-13T08:00:00Z",source:"ECB",convention:"EUR_PER_FOREIGN_UNIT",rates:{EUR:{currency:"EUR",eurPerForeignUnit:1,referenceDate:"2026-08-13",fetchedAt:"x",source:"ECB",convention:"EUR_PER_FOREIGN_UNIT"},GBP:{currency:"GBP",eurPerForeignUnit:1.16,referenceDate:"2026-08-13",fetchedAt:"x",source:"ECB",convention:"EUR_PER_FOREIGN_UNIT"},SEK:{currency:"SEK",eurPerForeignUnit:.09,referenceDate:"2026-08-13",fetchedAt:"x",source:"ECB",convention:"EUR_PER_FOREIGN_UNIT"}}};
const tx=(type,amount,extra={})=>({transactionType:type,transactionStatus:"RELEASED",postedDate:"2026-08-10T10:00:00Z",totalAmount:{currencyAmount:amount,currencyCode:"EUR"},marketplaceDetails:{marketplaceId:"ES",marketplaceName:"ES"},relatedIdentifiers:[{relatedIdentifierName:"ORDER_ID",relatedIdentifierValue:`order-${type}`}],breakdowns:[{breakdownType:"ProductCharges",breakdownAmount:{currencyAmount:100,currencyCode:"EUR"},breakdowns:[{breakdownType:"Commission",breakdownAmount:{currencyAmount:-15,currencyCode:"EUR"}}]}],...extra});
const base={productId:"p",sku:"sku",asin:"asin",marketplace:"ES",marketplaceId:"ES",fulfillmentChannel:"FBA",currency:"EUR",unitsMtd:2,rate7:2,rate14:1,rate30:.5,remainingDays:10,weights:{days7:.5,days14:.3,days30:.2},realizedPriceMtd:100,stockValue:null,stockFreshness:"STALE",referralFeePerUnit:15,fulfillmentFeePerUnit:5,feeSource:"PRODUCT_FEES_API",storageKnown:0,ecb};
const meta={asOfDate:"2026-08-13",periodStart:"2026-08-01",periodEnd:"2026-08-31"};

test("1 REAL_MTD uses transaction totalAmount",()=>assert.equal(buildAmazonRealMtd({transactions:[tx("Shipment",70)],periodStart:"2026-08-01",periodEnd:"2026-08-31",ecb}).marketplaces[0].nativeAmount,70));
test("2 breakdowns explain but never duplicate total",()=>assert.equal(buildAmazonRealMtd({transactions:[tx("Shipment",70)],periodStart:"2026-08-01",periodEnd:"2026-08-31",ecb}).marketplaces[0].nativeAmount,70));
test("3 Refund subtracts through signed total",()=>assert.equal(buildAmazonRealMtd({transactions:[tx("Refund",-25)],periodStart:"2026-08-01",periodEnd:"2026-08-31",ecb}).marketplaces[0].nativeAmount,-25));
test("4 positive Adjustment adds",()=>assert.equal(buildAmazonRealMtd({transactions:[tx("Adjustment",12)],periodStart:"2026-08-01",periodEnd:"2026-08-31",ecb}).marketplaces[0].nativeAmount,12));
test("5 ProductAdsPayment is REAL_MTD only",()=>{const real=buildAmazonRealMtd({transactions:[tx("ProductAdsPayment",-9)],periodStart:"2026-08-01",periodEnd:"2026-08-31",ecb});assert.equal(real.lines[0].transactionType,"ProductAdsPayment");assert.ok(buildAmazonFutureProductLine(base,meta).gaps.includes("ADS"));});

const feePayload=(promotion=0)=>({payload:{FeesEstimateResult:{Status:"Success",FeesEstimate:{TimeOfFeesEstimation:"2026-08-13T00:00:00Z",FeeDetailList:[{FeeType:"ReferralFee",FeeAmount:{CurrencyCode:"EUR",Amount:15},FinalFee:{CurrencyCode:"EUR",Amount:15},FeePromotion:{CurrencyCode:"EUR",Amount:0}},{FeeType:"FBAFees",FeeAmount:{CurrencyCode:"EUR",Amount:5},FinalFee:{CurrencyCode:"EUR",Amount:5-promotion},FeePromotion:{CurrencyCode:"EUR",Amount:promotion}}]}}}});
const feeInput={identifier:"x",marketplaceId:"ES",idValue:"sku",listingPrice:{CurrencyCode:"EUR",Amount:100},isAmazonFulfilled:true};
test("6 Product Fees extracts referral",async()=>{resetProductFeesCacheForTests();const c=createProductFeesClient(async()=>feePayload());assert.equal((await c.getMyFeesEstimateForSKU(feeInput)).referralFeePerUnit,15);});
test("7 Product Fees extracts FBA fulfillment",async()=>{resetProductFeesCacheForTests();const c=createProductFeesClient(async()=>feePayload());assert.equal((await c.getMyFeesEstimateForSKU(feeInput)).fulfillmentFeePerUnit,5);});
test("8 batch Product Fees supports multiple estimates",async()=>{resetProductFeesCacheForTests();const c=createProductFeesClient(async()=>[feePayload().payload,feePayload().payload]);const out=await c.getMyFeesEstimates([{...feeInput,idType:"SellerSKU"},{...feeInput,identifier:"y",idType:"SellerSKU",idValue:"sku2"}]);assert.equal(out.length,2);});
test("9 API failure leaves Fee Preview parser available",()=>{const rows=parseFbaFeePreview("sku\tfnsku\tasin\tamazon-store\tcurrency\testimated-referral-fee-per-unit\texpected-domestic-fulfilment-fee-per-unit\testimated-fee-total\na\tf\tb\tES\tEUR\t15\t5\t20",{reportId:"r",observedAt:"now"});assert.equal(rows[0].source,"FBA_FEE_PREVIEW_REPORT");});
test("10 temporary promotions do not reduce standard forecast fee",async()=>{resetProductFeesCacheForTests();const c=createProductFeesClient(async()=>feePayload(5));const out=await c.getMyFeesEstimateForSKU(feeInput);assert.equal(out.totalFeePerUnit,20);assert.equal(out.promotionalFinalFeePerUnit,15);});
test("11 realized MTD price precedes target",()=>assert.equal(buildAmazonFutureProductLine({...base,targetPrice:200},meta).priceSource,"REALIZED_MTD"));
test("12 stale stock does not cap to zero",()=>assert.ok(buildAmazonFutureProductLine({...base,stockValue:0,stockFreshness:"STALE"},meta).forecastUnits>0));
test("13 fresh stock caps forecast",()=>assert.equal(buildAmazonFutureProductLine({...base,stockValue:3,stockFreshness:"FRESH"},meta).forecastUnits,3));
test("14 REAL_MTD and FUTURE_REMAINDER coexist",()=>{const real=buildAmazonRealMtd({transactions:[tx("Shipment",70)],periodStart:"2026-08-01",periodEnd:"2026-08-31",ecb});const out=buildAmazonEconomicForecastV2({asOfDate:meta.asOfDate,periodStart:meta.periodStart,periodEnd:meta.periodEnd,real,future:[buildAmazonFutureProductLine(base,meta)]});assert.equal(out.marketplaces[0].expectedMonthNetEur,out.marketplaces[0].realNetMtdEur+out.marketplaces[0].futureNetKnownEur);});
test("15 V2 source identity cannot collide with legacy monthly forecast",()=>assert.match(buildAmazonFutureProductLine(base,meta).sourceKey,/^forecast-v2:ES:2026-08-13:/));
test("16 V2 source does not read 0.75 or amazon_expected_net_ratio",async()=>{const source=await readFile(new URL("./amazonEconomicForecastV2.ts",import.meta.url),"utf8");assert.doesNotMatch(source,/amazon_expected_net_ratio|gross\s*\*\s*0\.75/);});
test("17 GBP and SEK use estimated ECB FX",()=>{assert.equal(buildAmazonFutureProductLine({...base,currency:"GBP"},meta).fxSource,"ECB");assert.equal(buildAmazonFutureProductLine({...base,currency:"SEK"},meta).fxSource,"ECB");});
test("18 V2 has no cash movement",async()=>{const source=await readFile(new URL("./amazonEconomicForecastV2.ts",import.meta.url),"utf8");assert.doesNotMatch(source,/finance_cash_movements|cash_account/);});
test("19 V2 has no RECEIVED transition",async()=>{const source=await readFile(new URL("./buildAmazonEconomicForecastV2.ts",import.meta.url),"utf8");assert.doesNotMatch(source,/finance_receive_amazon_income|RECEIVED/);});
test("20 V2 does not mutate treasury",()=>assert.equal(buildAmazonEconomicForecastV2({asOfDate:meta.asOfDate,periodStart:meta.periodStart,periodEnd:meta.periodEnd,real:{lines:[],marketplaces:[]},future:[]}).doesNotMutateTreasury,true));

