import { listTransactions } from "@/modules/amazon-sp-api/financesClient";
import { productFeesClient, type ProductFeesInput } from "@/modules/amazon-sp-api/productFeesClient";
import { feePreviewByAsin,feePreviewBySku,FBA_FEE_PREVIEW_REPORT_TYPE,parseFbaFeePreview } from "@/modules/amazon-sp-api/fbaFeePreviewService";
import { downloadReportDocument,getReportDocument,listReports } from "@/modules/amazon-sp-api/reportsClient";
import { extractTwinlySkuFromSellerSku } from "@/modules/imports/shared/twinlySku";
import { getLatestEcbFxTable } from "./ecbFxService";
import { buildAmazonEconomicForecastV2,buildAmazonFutureProductLine,buildAmazonRealMtd,type FeeSource } from "./amazonEconomicForecastV2";
import { readAmazonDailySalesFallbackAdmin,readAmazonSalesEvidenceAdmin,readLatestFeePreviewContentAdmin,readLatestOperationalFbaStockAdmin,readTargetPricesAdmin } from "../repositories/amazonEconomicForecastV2Repository";
import { allocateOperationalFbaStock } from "./operationalFbaStockAllocation";

const MARKETPLACE_ID:Record<string,string|undefined>={ES:process.env.AMAZON_MARKETPLACE_ES,FR:process.env.AMAZON_MARKETPLACE_FR,DE:process.env.AMAZON_MARKETPLACE_DE,IT:process.env.AMAZON_MARKETPLACE_IT,GB:process.env.AMAZON_MARKETPLACE_GB,PL:process.env.AMAZON_MARKETPLACE_PL,SE:process.env.AMAZON_MARKETPLACE_SE};
const MARKETPLACE_NAME_BY_ID=()=>new Map(Object.entries(MARKETPLACE_ID).filter((entry):entry is [string,string]=>Boolean(entry[1])).map(([code,id])=>[id,code]));
function date(value:Date){return value.toISOString().slice(0,10);}
function daysAgo(now:Date,days:number){const out=new Date(now);out.setUTCDate(out.getUTCDate()-days);return date(out);}
function validSale(row:{order_status:string;item_status:string}){const text=`${row.order_status} ${row.item_status}`.toLowerCase();return !/cancel|cancell|annull|refunded/.test(text);}
function average(rows:Array<{quantity:number;item_price:number;item_tax:number;shipping_price:number;gift_wrap_price:number}>){const units=rows.reduce((sum,row)=>sum+Number(row.quantity||0),0);const amount=rows.reduce((sum,row)=>sum+Number(row.item_price||0)+Number(row.item_tax||0)+Number(row.shipping_price||0)+Number(row.gift_wrap_price||0),0);return units>0?amount/units:null;}
function sumUnits(rows:Array<{quantity:number}>){return rows.reduce((sum,row)=>sum+Number(row.quantity||0),0);}
export function resolveAmazonForecastWeights(){const parse=(key:string,fallback:number)=>{const n=Number(process.env[key]??fallback);return Number.isFinite(n)&&n>=0?n:fallback;};return{days7:parse("AMAZON_FORECAST_V2_WEIGHT_7D",0.5),days14:parse("AMAZON_FORECAST_V2_WEIGHT_14D",0.3),days30:parse("AMAZON_FORECAST_V2_WEIGHT_30D",0.2)};}
function maxStockAgeHours(){const value=Number(process.env.AMAZON_FORECAST_V2_MAX_STOCK_AGE_HOURS??48);return Number.isFinite(value)&&value>0?value:48;}
async function readFeePreviewEvidence(now:Date){const persisted=await readLatestFeePreviewContentAdmin();if(persisted)return persisted;const since=new Date(now);since.setUTCDate(since.getUTCDate()-14);const reports=await listReports({reportTypes:[FBA_FEE_PREVIEW_REPORT_TYPE],processingStatuses:["DONE"],createdSince:since.toISOString()});const latest=reports.sort((a,b)=>String(b.createdTime??"").localeCompare(String(a.createdTime??"")))[0];if(!latest?.reportDocumentId)return null;return{reportId:latest.reportId,observedAt:latest.processingEndTime??latest.createdTime??now.toISOString(),content:await downloadReportDocument(await getReportDocument(latest.reportDocumentId))};}

export async function buildAmazonEconomicForecastV2Live(options:{now?:Date}={}){
  const now=options.now??new Date(),asOfDate=date(now),periodStart=`${asOfDate.slice(0,7)}-01`,periodEnd=date(new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,0))),financeEnd=new Date(Math.min(now.getTime()-3*60000,new Date(`${asOfDate}T23:59:59Z`).getTime()));
  const [transactions,ecb,orderSales,preview]=await Promise.all([listTransactions({postedAfter:`${periodStart}T00:00:00Z`,postedBefore:financeEnd.toISOString()}),getLatestEcbFxTable(),readAmazonSalesEvidenceAdmin(daysAgo(now,30),asOfDate),readFeePreviewEvidence(now)]);const sales=orderSales.length?orderSales:await readAmazonDailySalesFallbackAdmin(daysAgo(now,30),asOfDate);
  const real=buildAmazonRealMtd({transactions,periodStart:`${periodStart}T00:00:00Z`,periodEnd:financeEnd.toISOString(),ecb});const marketplaceNameById=MARKETPLACE_NAME_BY_ID();for(const line of real.lines)line.marketplace=marketplaceNameById.get(line.marketplaceId)??line.marketplace;for(const row of real.marketplaces){const marketplaceId=row.lines[0]?.marketplaceId;row.marketplace=marketplaceId?marketplaceNameById.get(marketplaceId)??row.marketplace:row.marketplace;}const parsedPreview=preview?parseFbaFeePreview(preview.content,{reportId:preview.reportId,observedAt:preview.observedAt}):[];const previewRows=feePreviewBySku(parsedPreview),previewByAsin=feePreviewByAsin(parsedPreview);
  const cleanSales=sales.filter(row=>validSale(row)&&Boolean(extractTwinlySkuFromSellerSku(row.sku_original)||row.sku_limpio));const productIds=Array.from(new Set(cleanSales.map(row=>row.producto_id).filter((value):value is string=>Boolean(value))));const [targets,operationalStocks]=await Promise.all([readTargetPricesAdmin(productIds),readLatestOperationalFbaStockAdmin(productIds)]);
  const groups=new Map<string,typeof cleanSales>();for(const row of cleanSales){const key=[row.marketplace_country,row.sku_original,row.asin,row.fulfillment_channel,row.currency].join("|");const group=groups.get(key)??[];group.push(row);groups.set(key,group);}
  const evidence=Array.from(groups.entries()).map(([key,rows])=>{const [marketplace,sku,asin,channel,currency]=key.split("|");const mtd=rows.filter(row=>row.purchase_date>=periodStart),r7=rows.filter(row=>row.purchase_date>=daysAgo(now,7)),r14=rows.filter(row=>row.purchase_date>=daysAgo(now,14));return{marketplace,marketplaceId:MARKETPLACE_ID[marketplace]??"",sku,asin,fulfillmentChannel:/AFN|FBA|Amazon/i.test(channel)?"FBA" as const:"FBM" as const,currency,productId:rows[0].producto_id??`unmatched:${sku}`,unitsMtd:sumUnits(mtd),rate7:sumUnits(r7)/7,rate14:sumUnits(r14)/14,rate30:sumUnits(rows)/30,realizedPriceMtd:average(mtd),realizedPrice30d:average(rows),targetPrice:targets.get(rows[0].producto_id??"")??null};}).filter(row=>row.marketplaceId&&row.sku&&row.currency);
  const feeInputs:ProductFeesInput[]=evidence.slice(0,200).map((row,index)=>({identifier:`v2-${index}`,marketplaceId:row.marketplaceId,idType:orderSales.length?"SellerSKU" as const:"ASIN" as const,idValue:orderSales.length?row.sku:row.asin,listingPrice:{CurrencyCode:row.currency,Amount:row.realizedPriceMtd??row.realizedPrice30d??row.targetPrice??0},shipping:{CurrencyCode:row.currency,Amount:0},isAmazonFulfilled:row.fulfillmentChannel==="FBA"})).filter(row=>row.listingPrice.Amount>0&&row.idValue);
  const feeByIdentifier=new Map<string,Awaited<ReturnType<typeof productFeesClient.getMyFeesEstimates>>[number]>();for(let start=0;start<feeInputs.length;start+=20){const chunk=feeInputs.slice(start,start+20);try{for(const fee of await productFeesClient.getMyFeesEstimates(chunk))feeByIdentifier.set(fee.identifier,fee);}catch{/* Per-SKU report fallback below; gaps remain explicit. */}}
  const remainingDays=Math.max(0,Number(periodEnd.slice(8,10))-now.getUTCDate()),weights=resolveAmazonForecastWeights();const demandRows=evidence.map(row=>({...row,demandUnits:remainingDays*((row.rate7*weights.days7+row.rate14*weights.days14+row.rate30*weights.days30)/(weights.days7+weights.days14+weights.days30))}));const stockAllocations=allocateOperationalFbaStock(demandRows,operationalStocks,now,maxStockAgeHours());const future=evidence.map((row,index)=>{const api=feeByIdentifier.get(`v2-${index}`),report=previewRows.get(`${row.marketplace}|${row.sku}`)??previewByAsin.get(`${row.marketplace}|${row.asin}`),stock=stockAllocations[index];const feeSource:FeeSource=api?"PRODUCT_FEES_API":report?"FBA_FEE_PREVIEW_REPORT":"UNAVAILABLE";return buildAmazonFutureProductLine({...row,remainingDays,weights,listingPrice:null,stockValue:stock.stockValue,stockFreshness:stock.stockFreshness,stockObservedAt:stock.stockObservedAt,referralFeePerUnit:api?.referralFeePerUnit??report?.referralFeePerUnit??null,fulfillmentFeePerUnit:api?.fulfillmentFeePerUnit??report?.fulfillmentFeePerUnit??null,feeSource,feeObservedAt:api?.estimatedAt??report?.observedAt??null,storageKnown:0,ecb},{asOfDate,periodStart,periodEnd});});
  const forecast=buildAmazonEconomicForecastV2({asOfDate,periodStart,periodEnd,real,future});return{...forecast,weights,realTransactions:real.lines.length,details:future,gapsPolicy:{ads:"REAL_MTD_ONLY",awd:"REAL_MTD_ONLY",agl:"REAL_MTD_ONLY",futureRefunds:"OUT_OF_SCOPE",storage:"ZERO_UNLESS_AMAZON_FORECAST_AVAILABLE"}};
}
