import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
import { normalizePlannedMaturityInput, normalizePlannedMaturityPatchInput, plannedMaturityError } from "./creditLinePlannedMaturityValidation.ts";
import { createCreditReleaseTracker } from "../utils/creditLinePlannedRelease.ts";

const id="b24d9e3c-698c-4c14-bd1c-5c511b19e4d1";
test("validates finite canonical money and dates",()=>{
 const x=normalizePlannedMaturityInput({creditLineId:id,dueDate:"2026-08-17",plannedPrincipalEur:999999999999.99,expectedInterestEur:0,expectedFeesEur:0,concept:"Devolución",reference:null,notes:null,idempotencyKey:"one"});assert.equal(x.plannedPrincipalEur,999999999999.99);
 assert.throws(()=>normalizePlannedMaturityInput({...x,plannedPrincipalEur:1000000000000}));
 assert.throws(()=>normalizePlannedMaturityInput({...x,dueDate:"2026-02-30"}));
});
test("sanitizes database errors",()=>{assert.deepEqual(plannedMaturityError({code:"XX000",message:"secret SQL"}),{status:500,code:"INTERNAL_ERROR",error:"Unexpected finance error"});});
test("planning includes forecast without ledger writes",()=>{const s=fs.readFileSync(new URL("./buildFinancialPlanning.ts",import.meta.url),"utf8");assert.match(s,/credit_line_planned_maturity/);assert.match(s,/projectedCash -= event\.plannedCashOutEur/);const m=fs.readFileSync(new URL("../../../sql/migrations/20260804_04_credit_line_planned_maturities.sql",import.meta.url),"utf8");assert.doesNotMatch(m,/INSERT INTO public\.finance_credit_line_movements/);assert.doesNotMatch(m,/UPDATE public\.finance_credit_lines/);});
test("data script has 33 idempotent rows",()=>{const s=fs.readFileSync(new URL("../../../sql/data/20260804_credit_line_planned_maturities.sql",import.meta.url),"utf8");assert.equal((s.match(/gen_random_uuid\(\)/g)??[]).length,33);assert.match(s,/ON CONFLICT \(source_key\) DO NOTHING/);});
test("limits cumulative projected releases to current used capacity",()=>{const tracker=createCreditReleaseTracker([{id:"bbva",creditLimit:250000,availableAmount:165000},{id:"cr",creditLimit:600000,availableAmount:78500},{id:"lc",creditLimit:200000,availableAmount:65000}]);assert.equal(tracker.take("bbva",208900),85000);assert.equal(tracker.take("cr",588329),521500);assert.equal(tracker.take("lc",196000),135000);assert.equal(tracker.take("bbva",1),0);assert.equal(208900-85000+588329-521500+196000-135000,251729);});
test("PATCH contract omits line and idempotency key",()=>{const x=normalizePlannedMaturityPatchInput({dueDate:"2026-08-17",plannedPrincipalEur:1,expectedInterestEur:0,expectedFeesEur:0,concept:"Plan",reference:null,notes:null});assert.equal(x.plannedPrincipalEur,1);});
test("hardening uses advisory locking and accepts an empty spreadsheet schedule",()=>{const migration=fs.readFileSync(new URL("../../../sql/migrations/20260804_05_credit_line_planned_maturities_hardening.sql",import.meta.url),"utf8");assert.match(migration,/pg_advisory_xact_lock/);assert.match(migration,/PLANNED_MATURITY_SPREADSHEET_SOURCE_MISMATCH/);assert.doesNotMatch(migration,/v_updated\s*<>\s*33/);const data=fs.readFileSync(new URL("../../../sql/data/20260804_credit_line_planned_maturities.sql",import.meta.url),"utf8");assert.match(data,/PLANNED_MATURITY_SOURCE_CONFLICT/);assert.equal((data.match(/'spreadsheet_schedule','credit-maturity:/g)??[]).length,33);});

test("spreadsheet schedule is retired from operational planning",()=>{const repository=fs.readFileSync(new URL("../repositories/financialPlanningRepository.ts",import.meta.url),"utf8");assert.match(repository,/\.neq\("source_type", "spreadsheet_schedule"\)/);const migration=fs.readFileSync(new URL("../../../sql/migrations/20260808_02_close_legacy_opening_and_retire_spreadsheet_schedule.sql",import.meta.url),"utf8");assert.match(migration,/SPREADSHEET_SCHEDULE_RETIRED/);assert.match(migration,/before insert or update of source_type/i);});
test("planned maturity card never renders real-group placeholders",()=>{const ui=fs.readFileSync(new URL("../components/FinancialPlanningPage.tsx",import.meta.url),"utf8");const start=ui.indexOf("if (isPlannedCreditMaturity)");const end=ui.indexOf("\n  return (",start);const planned=ui.slice(start,end);assert.ok(start>0&&end>start);assert.match(planned,/Principal previsto/);assert.match(planned,/Salida total prevista/);assert.match(planned,/Crédito previsto a liberar/);assert.doesNotMatch(planned,/Pagado:/);assert.doesNotMatch(planned,/Sin vencimiento/);assert.doesNotMatch(planned,/repaymentGroupStatus/);});
