export const ECB_FX_CONVENTION = "EUR_PER_FOREIGN_UNIT" as const;
export const ECB_DAILY_URL = "https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml";
export type EcbFxRate={currency:string;eurPerForeignUnit:number;referenceDate:string;fetchedAt:string;source:"ECB";convention:typeof ECB_FX_CONVENTION};
export type EcbFxTable={referenceDate:string;fetchedAt:string;source:"ECB";convention:typeof ECB_FX_CONVENTION;rates:Record<string,EcbFxRate>};
let cached:{day:string;value:EcbFxTable}|null=null;
export function parseEcbDailyXml(xml:string,fetchedAt:string):EcbFxTable{const referenceDate=xml.match(/time=['"](\d{4}-\d{2}-\d{2})['"]/)?.[1];if(!referenceDate)throw new Error("ECB_REFERENCE_DATE_MISSING");const rates:Record<string,EcbFxRate>={};const pattern=/currency=['"]([A-Z]{3})['"]\s+rate=['"]([0-9.]+)['"]/g;let match:RegExpExecArray|null;while((match=pattern.exec(xml))!==null){const foreignPerEur=Number(match[2]);if(foreignPerEur>0)rates[match[1]]={currency:match[1],eurPerForeignUnit:1/foreignPerEur,referenceDate,fetchedAt,source:"ECB",convention:ECB_FX_CONVENTION};}rates.EUR={currency:"EUR",eurPerForeignUnit:1,referenceDate,fetchedAt,source:"ECB",convention:ECB_FX_CONVENTION};return {referenceDate,fetchedAt,source:"ECB",convention:ECB_FX_CONVENTION,rates};}
export async function getLatestEcbFxTable(options:{now?:Date;fetcher?:typeof fetch;signal?:AbortSignal}={}):Promise<EcbFxTable>{const now=options.now??new Date();const day=now.toISOString().slice(0,10);if(cached?.day===day)return cached.value;const response=await (options.fetcher??fetch)(ECB_DAILY_URL,{headers:{Accept:"application/xml"},cache:"no-store",signal:options.signal?AbortSignal.any([options.signal,AbortSignal.timeout(10_000)]):AbortSignal.timeout(10_000)});if(!response.ok)throw new Error(`ECB_FX_HTTP_${response.status}`);const value=parseEcbDailyXml(await response.text(),now.toISOString());cached={day,value};return value;}
export function resetEcbFxCacheForTests(){cached=null;}
export function valueAmazonAmountEur(currency:string,amount:number,converted?:{CurrencyCode?:string;CurrencyAmount?:number},ecb?:EcbFxTable|null,realizedAt?:string|null){const convertedAmount=Number(converted?.CurrencyAmount);if(converted?.CurrencyCode?.toUpperCase()==="EUR"&&Number.isFinite(convertedAmount))return {amountEur:convertedAmount,officialAmountEur:convertedAmount,realizedAmountEur:convertedAmount,realizedFxRate:amount!==0?convertedAmount/amount:null,estimatedFxRate:null,fxSource:"AMAZON_CONVERTED_TOTAL",fxKind:"AMAZON_REALIZED_FX" as const,fxObservedAt:realizedAt??null};if(currency==="EUR")return {amountEur:amount,officialAmountEur:amount,realizedAmountEur:null,realizedFxRate:null,estimatedFxRate:1,fxSource:"EUR_IDENTITY",fxKind:"ERP_ESTIMATED_FX" as const,fxObservedAt:ecb?.referenceDate??null};const rate=ecb?.rates[currency];if(rate)return {amountEur:amount*rate.eurPerForeignUnit,officialAmountEur:null,realizedAmountEur:null,realizedFxRate:null,estimatedFxRate:rate.eurPerForeignUnit,fxSource:"ECB",fxKind:"ERP_ESTIMATED_FX" as const,fxObservedAt:rate.referenceDate};return {amountEur:null,officialAmountEur:null,realizedAmountEur:null,realizedFxRate:null,estimatedFxRate:null,fxSource:"UNAVAILABLE",fxKind:"UNAVAILABLE" as const,fxObservedAt:null};}
